"""Add password and created_at

Revision ID: 258172c96ac7
Revises: 31dc1284cbcb
Create Date: 2026-06-29 11:49:57.435255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258172c96ac7'
down_revision = '31dc1284cbcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
