"""add authlib oauth fields

Revision ID: 82c6f65e644e
Revises: 89b0caec1118
Create Date: 2026-07-01 20:47:10.371658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82c6f65e644e'
down_revision = '89b0caec1118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('github_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('oauth_id')
        batch_op.drop_column('oauth_provider')

    # Update existing records to avoid NullViolation
    op.execute("UPDATE users SET provider = 'email' WHERE provider IS NULL")
    op.execute("UPDATE users SET updated_at = NOW() WHERE updated_at IS NULL")

    # Alter provider column to be NOT NULL
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('provider', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('oauth_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('provider')
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('github_id')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
