"""add resume analysis field

Revision ID: 942033bfd163
Revises: f6552ad46603
Create Date: 2026-07-02 10:19:10.595478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '942033bfd163'
down_revision = 'f6552ad46603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analysis', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_column('analysis')

    # ### end Alembic commands ###
